apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.component_id }}
  {%- if values.description %}
  description: ${{ values.description | dump }}
  {%- endif %}
  tags:
    - gcp
    - gke
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: ${{ values.destination.owner + "/" + values.destination.repo }}
spec:
  type: kubernetes
  lifecycle: experimental
  owner: ${{ values.owner | dump }}
